run:
  deadline: 1m
  issues-exit-code: 1
  modules-download-mode: readonly
  tests: true
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-occurrences: 5
  goimports:
    local-prefixes: github.com/jaimem88/zearch

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - goconst
    - gocyclo
    - goimports
    - golint
    - gosimple
    - govet
    - gosec
    - ineffassign
    - misspell
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
  fast: false
