name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    name: unit tests
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: unit tests
        run: make test

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: coverage
        run: make cover
